webtalk_init -webtalk_dir P:/CS214-Computer-Organization/CS214-Computer-Organization-Project/verilog/verilog.sim/sim_1/behav/xsim/xsim.dir/cpu_sim_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sat May 27 04:24:17 2023" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "89fd0f7c-eb87-4187-90dd-11a51d4d593a" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "458b95beae8e49dca08af74bec2f4b3b" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "121" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 6800H with Radeon Graphics         " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3194 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "26" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "731 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "62 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "706" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "37" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip unimacro_ver unisims_ver " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "1.89_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "144724_KB" -context "xsim\\usage"
webtalk_transmit -clientid 153212020 -regid "" -xml P:/CS214-Computer-Organization/CS214-Computer-Organization-Project/verilog/verilog.sim/sim_1/behav/xsim/xsim.dir/cpu_sim_behav/webtalk/usage_statistics_ext_xsim.xml -html P:/CS214-Computer-Organization/CS214-Computer-Organization-Project/verilog/verilog.sim/sim_1/behav/xsim/xsim.dir/cpu_sim_behav/webtalk/usage_statistics_ext_xsim.html -wdm P:/CS214-Computer-Organization/CS214-Computer-Organization-Project/verilog/verilog.sim/sim_1/behav/xsim/xsim.dir/cpu_sim_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
