# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: new/cpu.xdc

# IP: ip/RAM/RAM.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==RAM || ORIG_REF_NAME==RAM} -quiet] -quiet

# IP: ip/prgrom/prgrom.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==prgrom || ORIG_REF_NAME==prgrom} -quiet] -quiet

# IP: ip/uart_bmpg_0_1/uart_bmpg_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==uart_bmpg_0 || ORIG_REF_NAME==uart_bmpg_0} -quiet] -quiet
