# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg.xci
# IP: The module: 'clkout_upg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg.xci
# IP: The module: 'clkout_upg' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: p:/CS214-Computer-Organization/Project-uart/verilog/verilog.srcs/sources_1/ip/clkout_upg/clkout_upg_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clkout_upg'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
