# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tfgg484-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.cache/wt [current_project]
set_property parent.project_path E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo e:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/dmem32.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_keybd.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/dmem32_keybd.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_kbt.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/dmem32_kbt.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_keybd2.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_key_main.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_keybd_main12.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_fullscene1_key.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_withoutlatency.coe}}
add_files {{E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_scene1.coe}}
add_files {{e:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/imports/Chrome Download/prgmip32_keyboardscene.coe}}
read_verilog -library xil_defaultlib {
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/Executs32.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/FracFrequency.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/IFetch.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/LedIO.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/MemOrIO.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/SwitchIO.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/controller.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/dmemory32.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/idcoder32.v
  E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/new/cpu.v
}
read_ip -quiet E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/ip/RAM/RAM.xci
set_property used_in_implementation false [get_files -all e:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/ip/RAM/RAM_ooc.xdc]

read_ip -quiet E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/ip/prgrom/prgrom.xci
set_property used_in_implementation false [get_files -all e:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/sources_1/ip/prgrom/prgrom_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/constrs_1/new/CPU_con.xdc
set_property used_in_implementation false [get_files E:/Gitrepo/CPU-project-of-Computer-Organization/project_2/project_2.srcs/constrs_1/new/CPU_con.xdc]


synth_design -top cpu -part xc7a100tfgg484-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef cpu.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file cpu_utilization_synth.rpt -pb cpu_utilization_synth.pb"
